"""Geometry conversion and H3 resolution utilities."""

from crc_framework import lookup_continent, lookup_geography, lookup_ipcc_region

from .admin import (
    LookupCatalog,
    enrich_adm2_with_adm1,
    enrich_adm2_with_adm1_sql,
    write_lookup_contract,
    write_partitioned_lookup,
)
from .coverage import (
    build_border_hexes_sql,
    build_candidates_sql,
    build_coverage_sql,
    build_edge_hexes_sql,
    build_hex_counts_sql,
    materialize_cell_geometries_sql,
    materialize_edge_hexes,
    missing_cell_wkt_sql,
    recommend_parent_resolution,
    write_exploded_coverage,
    write_hierarchical_coverage,
)
from .formats import FormatAdapter, GeoFormat
from .h3 import (
    H3Indexer,
    PolyfillMode,
    ResolutionEstimate,
    average_edge_length_m,
    cell_polygon,
    estimate_resolutions,
    intersecting_cells,
    max_pixel_spacing_m,
    pixel_grid_resolution,
    point_to_cell,
    reduce_h3_values,
    sample_grid_to_h3,
    subsample_offsets,
)
from .pmtiles import (
    AREAS,
    POINTS,
    POLYGONS,
    POLYGONS_CAPPED,
    PMTilesBuild,
    PMTilesLayer,
    PMTilesResult,
    TilingBudget,
    TippecanoePreset,
    ZoomRange,
    check_tiling_budget,
    coerce_zoom_range,
    measure_source,
    require_tile_join,
    require_tippecanoe,
    tippecanoe_command,
)
from .vector import VectorContainment, expand_polygon_candidates, polyfill_wkb

__all__ = [
    "AREAS",
    "FormatAdapter",
    "GeoFormat",
    "H3Indexer",
    "LookupCatalog",
    "PMTilesBuild",
    "PMTilesLayer",
    "PMTilesResult",
    "POINTS",
    "POLYGONS",
    "POLYGONS_CAPPED",
    "PolyfillMode",
    "ResolutionEstimate",
    "TilingBudget",
    "TippecanoePreset",
    "VectorContainment",
    "ZoomRange",
    "average_edge_length_m",
    "build_border_hexes_sql",
    "build_candidates_sql",
    "build_coverage_sql",
    "build_edge_hexes_sql",
    "build_hex_counts_sql",
    "cell_polygon",
    "check_tiling_budget",
    "coerce_zoom_range",
    "enrich_adm2_with_adm1",
    "enrich_adm2_with_adm1_sql",
    "estimate_resolutions",
    "expand_polygon_candidates",
    "intersecting_cells",
    "lookup_continent",
    "lookup_geography",
    "lookup_ipcc_region",
    "materialize_cell_geometries_sql",
    "materialize_edge_hexes",
    "max_pixel_spacing_m",
    "measure_source",
    "missing_cell_wkt_sql",
    "pixel_grid_resolution",
    "point_to_cell",
    "polyfill_wkb",
    "recommend_parent_resolution",
    "reduce_h3_values",
    "require_tile_join",
    "require_tippecanoe",
    "sample_grid_to_h3",
    "subsample_offsets",
    "tippecanoe_command",
    "write_exploded_coverage",
    "write_hierarchical_coverage",
    "write_lookup_contract",
    "write_partitioned_lookup",
]
