"""Cross-module analytical workflows."""

from .distributions import (
    CURVE_COLUMNS,
    curve_parameters_from_row,
    curve_quantiles,
    distribution_from_hazard_row,
    return_period_value_columns,
    return_periods_to_probabilities,
    stream_curve_quantiles_wide_to_parquet,
)
from .jrc import (
    JRCAreaPlan,
    JRCCanonicalizationPlan,
    JRCFloodPolicy,
    JRCPortfolioEvaluation,
    JRCSourcePlan,
    MaterializationResult,
    PrefetchResult,
)
from .portfolio import (
    PORTFOLIO_METADATA_KEY,
    AssetPortfolio,
    CellColumn,
    ExecutionOptions,
    HazardDataset,
    HazardSelection,
    ImpactContextColumns,
    PointColumns,
    PortfolioEvaluation,
    PortfolioEvaluationResult,
)
from .tiling import (
    OSClimateSelectionSpec,
    curve_quantiles_at,
    run_tiled_canonicalization,
    stream_curve_quantiles_to_parquet,
    tile_bounds,
)

__all__ = [
    "AssetPortfolio",
    "CellColumn",
    "CURVE_COLUMNS",
    "ExecutionOptions",
    "HazardDataset",
    "HazardSelection",
    "ImpactContextColumns",
    "JRCAreaPlan",
    "JRCCanonicalizationPlan",
    "JRCFloodPolicy",
    "JRCPortfolioEvaluation",
    "JRCSourcePlan",
    "MaterializationResult",
    "OSClimateSelectionSpec",
    "PORTFOLIO_METADATA_KEY",
    "PointColumns",
    "PrefetchResult",
    "PortfolioEvaluation",
    "PortfolioEvaluationResult",
    "curve_parameters_from_row",
    "curve_quantiles",
    "curve_quantiles_at",
    "distribution_from_hazard_row",
    "return_period_value_columns",
    "return_periods_to_probabilities",
    "run_tiled_canonicalization",
    "stream_curve_quantiles_to_parquet",
    "stream_curve_quantiles_wide_to_parquet",
    "tile_bounds",
]
